name: build

on:
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@main

            - name: setup pybuild
              uses: pybuild-org/pybuild@main

            - name: run build
              run: pybuild pybuild.xml

            - name: get time
              run: echo "RELEASE_TIME=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

            - name: create release
              uses: softprops/action-gh-release@master

              with:
                  tag_name: ${{ env.RELEASE_TIME }}
                  name: ${{ env.RELEASE_TIME }}
                  draft: false
                  prerelease: false
                  files: dist/*

              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
